version: '2'

services:

  node_app:
    container_name: node-app
    volumes:
     - ./app:/var/www/app/
    build:
      context: ./
      #context: ./dockerfiles/
      dockerfile: ./dockerfiles/alpine.node.dockerfile.sh
    
    command: npm start
    
    image: cntmedia/alpine.node:latest
    #image: cntmedia/alpine.node:6.9.1
    expose:
      - 8080
    ports:
      - 80:8080
