version: '2'

services:

  angular_app:
    container_name: node
    volumes:
     - ./app:/var/www/app/
    build:
      context: ./
      #context: ./dockerfiles/
      dockerfile: ./dockerfiles/node.dockerfile.sh

    image: cntmedia/node:latest
    #image: cntmedia/node:6.9.1
    expose:
      - 8080
    ports:
      - 80:8080
